server:
  port: 8081

 
 
   
  #ssl:
   # key-store: keystore.p12
   # key-store-password: 6286865
   # keyStoreType: PKCS12
   # keyAlias: tomcat
  servlet:
    encoding:
      force-response: true
  
    

spring:
 
  datasource:
    driver-classname: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring5fs?serverTimezone=Asia/Seoul
    username: spring5
    password: spring5
    connection-timeout:  10000
    maximum-pool-size: 10
  jpa:
   properties:
    default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    show-sql: true
  
  data:
   redis:
    host: localhost
    port: 6379
    type: redis
    
    
  mail:
   host: smtp.gmail.com
   port: 587
   username: dlwjdwns424@gmail.com
   password: uhkiiunbzpihbpjj
   properties:
     mail:
       smtp:
         auth: true
         timeout: 5000
         starttls:
           enable: true  
      
  security:
    oauth2:
      client:
        registration:
         google:  #/oauth2/authorization/google
           client-id: 1097190533646-mupo2mme88dmbddh28pqnu06qlgtl72g.apps.googleusercontent.com
           client-secret: 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
           scope:
           - email
           - profile
           redirect-uri: http://localhost:8081/callback/google
        
         naver:
            client-id: aY5fEqz6k3UICKF1yiqt
            client-secret: _92K9jefN4
            scope:
            - name
            - email
            
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/callback/naver
            
            
            
        provider:
           naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
            
            
secret:
 jwtkey:skdjfkjsdklfjdsklfjklsdjfkljskemtklemwrklwmekrjkjrio3i3jirjk3kr
 
   
   
   
   
   
            
      